apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - blackbox-deployment.yaml
  - blackbox-service.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml
      - alerts.yml
  - name: blackbox-config
    files:
      - blackbox.yml
