global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: argocd-application-controller
    static_configs:
      - targets: [argocd-metrics.argocd.svc.cluster.local:8082]

  - job_name: argocd-server
    static_configs:
      - targets: [argocd-server-metrics.argocd.svc.cluster.local:8083]

  - job_name: argocd-repo-server
    static_configs:
      - targets: [argocd-repo-server.argocd.svc.cluster.local:8084]

  - job_name: retail-ui-nodeport
    metrics_path: /probe
    scrape_interval: 30s
    scrape_timeout: 15s
    params:
      module: [http_200]
    static_configs:
      - targets: ['http://192.168.88.5:32065/']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter.observability.svc.cluster.local:9115
