global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: argocd-application-controller
    static_configs:
      - targets: [argocd-metrics.argocd.svc.cluster.local:8082]

  - job_name: argocd-server
    static_configs:
      - targets: [argocd-server-metrics.argocd.svc.cluster.local:8083]
