apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: observability
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 4Gi
