apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail

resources:
  - ../../vendor
  - prune-probe.yaml

patches:
  - path: patches/ui-replicas.yaml
  - path: patches/ui-service-nodeport.yaml
  - path: patches/catalog-mysql-prune-confirm.yaml
  - path: patches/orders-postgresql-prune-confirm.yaml
  - path: patches/orders-rabbitmq-prune-confirm.yaml
