apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  template:
    spec:
      containers:
        - name: ui
          readinessProbe:
            httpGet:
              path: /stage6-intentional-readiness-failure
              port: 8080
