apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail

resources:
  - ../../../apps/retail
  - orders-postgresql-data.yaml

patches:
  - path: checkout-freeze.yaml
  - path: orders-freeze.yaml
  - path: orders-postgresql-cutover.yaml
