apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-postgresql-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  storageClassName: local-path-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
